language: python
group: travis_latest
dist: xenial
sudo: true

env:
    global:
        - global_1="global1"
        - CMDPREFIX="prefix_global"
    matrix:
        - matrix_config="config_1"      # seems like those variables are not expanded properly
        - matrix_config="config_2"      # seems like those variables are not expanded properly

matrix:
    include:
    #################################################################################
    - os: linux
      language: sh
      env:
          - test_matrix1=${matrix_config}               # fails !
          - CMDPREFIX="prefix_matrix1"
      name: "Matrix1 - Config: ${matrix_config}"        # fails !
      before_install:
          # I want to do something like:
          # - if [[ ${matrix_config} == "config_1" ]]; then <do_something>; fi
          # - if [[ ${matrix_config} == "config_2" ]]; then <do_something>; fi

          - set test_matrix1_1=${matrix_config} # fails !
          - printenv
    #################################################################################
    - os: linux
      language: sh
      env:
          - test_matrix2=${matrix_config}
          - CMDPREFIX="prefix_matrix2"
      name: "Matrix2 - Config: ${matrix_config}"
      before_install:
          # I want to do something like:
          # - if [[ ${matrix_config} == "config_1" ]]; then <do_something>; fi
          # - if [[ ${matrix_config} == "config_2" ]]; then <do_something>; fi
          - set test_matrix2_1=${matrix_config}
          - printenv
    #################################################################################

script:
    - ${CMDPREFIX} call_a_function_that_fails
    - ${global_1} call_a_function_that_fails
    - ${matrix_config} call_a_function_that_fails       # fails !
    - printenv
