language: python
group: travis_latest
dist: xenial
sudo: true

env:
    global:
        - global_1="global1"
        - CMDPREFIX="prefix_global"
    matrix:
        - matrix_config="config_1"
        - matrix_config="config_2"

matrix:
    include:
    #################################################################################
    - os: linux
      language: sh
      env:
          - test_matrix1=${matrix_config}
          - CMDPREFIX="prefix_matrix1"
      name: "Matrix1 - ${matrix_config}"
      before_install:
          - set test_matrix1_1=${matrix_config}
          - printenv
    #################################################################################
    - os: linux
      language: sh
      env:
          - test_matrix2=${matrix_config}
          - CMDPREFIX="prefix_matrix2"
      name: "Matrix2 - ${matrix_config}"
      before_install:
          - set test_matrix2_1=${matrix_config}
          - printenv
    #################################################################################

script:
    - ${CMDPREFIX} call_a_function_that_fails
    - ${global_1} call_a_function_that_fails
    - printenv
