language: python
group: travis_latest
dist: xenial
sudo: true

env:
    global:
        - github_master="https://github.com/${TREVIS_REPO_SLUG}/archive/master.zip"   ## not working - ${TREVIS_REPO_SLUG} is not expanded
        - global_test="global_variable_TEST"
    matrix:
        - matrix_test="matrix_variable_TEST1"
        - matrix_test="matrix_variable_TEST2"

    #################################################################################
matrix:
    include:
    #################################################################################
    - os: linux
      language: sh
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - env_variable_within_matrix="variable_in_matrix_scope_TEST3"
      name: "TEST1, ${matrix_test}, "
      before_install:
          - export github_master2="https://github.com/${TREVIS_REPO_SLUG}/archive/master.zip"  ## not working - ${TREVIS_REPO_SLUG} is not expanded
          - printenv

    #################################################################################
    - os: linux
      language: sh
      name: "TEST1, ${matrix_test}, ${global_test}, ${env_variable_within_matrix}, $matrix_test, $global_test, $env_variable_within_matrix"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
      before_install:
          - printenv

before_install:
    - export github_master4="https://github.com/${TREVIS_REPO_SLUG}/archive/master.zip"

script:
    - export github_master5="https://github.com/${TREVIS_REPO_SLUG}/archive/master.zip"
    - ${CMDPREFIX} call_a_function_that_fails
    - ${global_test} call_a_function_that_fails
    - $global_test call_a_function_that_fails
    - ${matrix_test} call_a_function_that_fails
    - $matrix_test call_a_function_that_fails
    - ${env_variable_within_matrix} call_a_function_that_fails
    - $env_variable_within_matrix call_a_function_that_fails
    - printenv
